// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package performancetool.proxies;

public enum Level
{
	CRITICAL(new String[][] { new String[] { "en_US", "Critical" }, new String[] { "nl_NL", "Kritiek" }, new String[] { "de_DE", "Kritisch" } }),
	ERROR(new String[][] { new String[] { "en_US", "Error" }, new String[] { "nl_NL", "Fout" }, new String[] { "de_DE", "Fehler " } }),
	WARNING(new String[][] { new String[] { "en_US", "Warning" }, new String[] { "nl_NL", "Waarschuwing" }, new String[] { "de_DE", "Warnung" } }),
	INFO(new String[][] { new String[] { "en_US", "Info" }, new String[] { "nl_NL", "Info" }, new String[] { "de_DE", "Info" } }),
	DEBUG(new String[][] { new String[] { "en_US", "Debug" }, new String[] { "nl_NL", "Debug" }, new String[] { "de_DE", "Debug" } }),
	TRACE(new String[][] { new String[] { "en_US", "Trace" }, new String[] { "nl_NL", "Trace" }, new String[] { "de_DE", "Spur " } });

	private java.util.Map<String,String> captions;

	private Level(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
