// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package performancetool.proxies;

public enum PerformanceTypeEnum
{
	Microflow(new String[][] { new String[] { "en_US", "Microflow" }, new String[] { "nl_NL", "Microflow" } }),
	Client_API(new String[][] { new String[] { "en_US", "Client API" }, new String[] { "nl_NL", "Client API" } });

	private java.util.Map<String,String> captions;

	private PerformanceTypeEnum(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
