// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pizzamario.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the PizzaMario module

	public static void addSelectedToppingToPizza(IContext context, pizzamario.proxies.Topping _topping, pizzamario.proxies.ExtraTopping _extraTopping)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Topping", _topping == null ? null : _topping.getMendixObject());
			params.put("ExtraTopping", _extraTopping == null ? null : _extraTopping.getMendixObject());
			Core.execute(context, "PizzaMario.AddSelectedToppingToPizza", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean bCo_SetRandom(IContext context, pizzamario.proxies.Topping _topping)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Topping", _topping == null ? null : _topping.getMendixObject());
			return (Boolean)Core.execute(context, "PizzaMario.BCo_SetRandom", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean bCo_Topping_UpdateToppingName(IContext context, pizzamario.proxies.Topping _topping)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Topping", _topping == null ? null : _topping.getMendixObject());
			return (Boolean)Core.execute(context, "PizzaMario.BCo_Topping_UpdateToppingName", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void cleanGeneratedData(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "PizzaMario.CleanGeneratedData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void createRandomOrdersForPratchett(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "PizzaMario.CreateRandomOrdersForPratchett", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void customer_NewOrder(IContext context, pizzamario.proxies.Customer _customer)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Customer", _customer == null ? null : _customer.getMendixObject());
			Core.execute(context, "PizzaMario.Customer_NewOrder", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void customer_Upgrade(IContext context, pizzamario.proxies.Customer _customer)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Customer", _customer == null ? null : _customer.getMendixObject());
			Core.execute(context, "PizzaMario.Customer_Upgrade", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void generateOrdersForPratchett(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "PizzaMario.GenerateOrdersForPratchett", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<pizzamario.proxies.Topping> gridSource_FavouriteToppings(IContext context, pizzamario.proxies.ExtraTopping _extraTopping)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ExtraTopping", _extraTopping == null ? null : _extraTopping.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "PizzaMario.GridSource_FavouriteToppings", params);
			java.util.List<pizzamario.proxies.Topping> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<pizzamario.proxies.Topping>();
				for (IMendixObject obj : objs)
					result.add(pizzamario.proxies.Topping.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void order_AddTopping(IContext context, pizzamario.proxies.OrderLine _orderLine)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("OrderLine", _orderLine == null ? null : _orderLine.getMendixObject());
			Core.execute(context, "PizzaMario.Order_AddTopping", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static Long vA_Order_Total(IContext context, pizzamario.proxies.Order _order)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Order", _order == null ? null : _order.getMendixObject());
			return (Long)Core.execute(context, "PizzaMario.VA_Order_Total", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}