// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pizzamario.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Customer
{
	private final IMendixObject customerMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PizzaMario.Customer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LastName("LastName"),
		DateOfBirth("DateOfBirth"),
		Status("Status"),
		PreferredPayment("PreferredPayment"),
		DefaultLocation("DefaultLocation"),
		Customer_Order("PizzaMario.Customer_Order");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Customer(IContext context)
	{
		this(context, Core.instantiate(context, "PizzaMario.Customer"));
	}

	protected Customer(IContext context, IMendixObject customerMendixObject)
	{
		if (customerMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("PizzaMario.Customer", customerMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PizzaMario.Customer");

		this.customerMendixObject = customerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Customer(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static pizzamario.proxies.Customer create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "PizzaMario.Customer");
		return new pizzamario.proxies.Customer(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Customer.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pizzamario.proxies.Customer initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pizzamario.proxies.Customer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pizzamario.proxies.Customer initialize(IContext context, IMendixObject mendixObject)
	{
		return new pizzamario.proxies.Customer(context, mendixObject);
	}

	public static pizzamario.proxies.Customer load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pizzamario.proxies.Customer.initialize(context, mendixObject);
	}

	public static java.util.List<pizzamario.proxies.Customer> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pizzamario.proxies.Customer> result = new java.util.ArrayList<pizzamario.proxies.Customer>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PizzaMario.Customer" + xpathConstraint))
			result.add(pizzamario.proxies.Customer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LastName
	 */
	public final String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final String getLastName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(IContext context, String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final pizzamario.proxies.Customer_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final pizzamario.proxies.Customer_Status getStatus(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return pizzamario.proxies.Customer_Status.valueOf((String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(pizzamario.proxies.Customer_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(IContext context, pizzamario.proxies.Customer_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * Set value of PreferredPayment
	 * @param preferredpayment
	 */
	public final pizzamario.proxies.PaymentTypes getPreferredPayment()
	{
		return getPreferredPayment(getContext());
	}

	/**
	 * @param context
	 * @return value of PreferredPayment
	 */
	public final pizzamario.proxies.PaymentTypes getPreferredPayment(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PreferredPayment.toString());
		if (obj == null)
			return null;

		return pizzamario.proxies.PaymentTypes.valueOf((String) obj);
	}

	/**
	 * Set value of PreferredPayment
	 * @param preferredpayment
	 */
	public final void setPreferredPayment(pizzamario.proxies.PaymentTypes preferredpayment)
	{
		setPreferredPayment(getContext(), preferredpayment);
	}

	/**
	 * Set value of PreferredPayment
	 * @param context
	 * @param preferredpayment
	 */
	public final void setPreferredPayment(IContext context, pizzamario.proxies.PaymentTypes preferredpayment)
	{
		if (preferredpayment != null)
			getMendixObject().setValue(context, MemberNames.PreferredPayment.toString(), preferredpayment.toString());
		else
			getMendixObject().setValue(context, MemberNames.PreferredPayment.toString(), null);
	}

	/**
	 * @return value of DefaultLocation
	 */
	public final String getDefaultLocation()
	{
		return getDefaultLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultLocation
	 */
	public final String getDefaultLocation(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DefaultLocation.toString());
	}

	/**
	 * Set value of DefaultLocation
	 * @param defaultlocation
	 */
	public final void setDefaultLocation(String defaultlocation)
	{
		setDefaultLocation(getContext(), defaultlocation);
	}

	/**
	 * Set value of DefaultLocation
	 * @param context
	 * @param defaultlocation
	 */
	public final void setDefaultLocation(IContext context, String defaultlocation)
	{
		getMendixObject().setValue(context, MemberNames.DefaultLocation.toString(), defaultlocation);
	}

	/**
	 * @return value of Customer_Order
	 */
	public final pizzamario.proxies.Order getCustomer_Order() throws CoreException
	{
		return getCustomer_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_Order
	 */
	public final pizzamario.proxies.Order getCustomer_Order(IContext context) throws CoreException
	{
		pizzamario.proxies.Order result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Customer_Order.toString());
		if (identifier != null)
			result = pizzamario.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Customer_Order
	 * @param customer_order
	 */
	public final void setCustomer_Order(pizzamario.proxies.Order customer_order)
	{
		setCustomer_Order(getContext(), customer_order);
	}

	/**
	 * Set value of Customer_Order
	 * @param context
	 * @param customer_order
	 */
	public final void setCustomer_Order(IContext context, pizzamario.proxies.Order customer_order)
	{
		if (customer_order == null)
			getMendixObject().setValue(context, MemberNames.Customer_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Customer_Order.toString(), customer_order.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return customerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pizzamario.proxies.Customer that = (pizzamario.proxies.Customer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PizzaMario.Customer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
