// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pizzamario.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Order
{
	private final IMendixObject orderMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PizzaMario.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		Payment("Payment"),
		Total("Total"),
		Location("Location"),
		IsGenerated("IsGenerated"),
		Order_Customer("PizzaMario.Order_Customer");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Order(IContext context)
	{
		this(context, Core.instantiate(context, "PizzaMario.Order"));
	}

	protected Order(IContext context, IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("PizzaMario.Order", orderMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PizzaMario.Order");

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Order(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static pizzamario.proxies.Order create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "PizzaMario.Order");
		return new pizzamario.proxies.Order(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Order.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pizzamario.proxies.Order initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pizzamario.proxies.Order.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pizzamario.proxies.Order initialize(IContext context, IMendixObject mendixObject)
	{
		return new pizzamario.proxies.Order(context, mendixObject);
	}

	public static pizzamario.proxies.Order load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pizzamario.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<pizzamario.proxies.Order> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pizzamario.proxies.Order> result = new java.util.ArrayList<pizzamario.proxies.Order>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PizzaMario.Order" + xpathConstraint))
			result.add(pizzamario.proxies.Order.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OrderNumber
	 */
	public final Long getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final Long getOrderNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(Long ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(IContext context, Long ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * Set value of Payment
	 * @param payment
	 */
	public final pizzamario.proxies.PaymentTypes getPayment()
	{
		return getPayment(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment
	 */
	public final pizzamario.proxies.PaymentTypes getPayment(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Payment.toString());
		if (obj == null)
			return null;

		return pizzamario.proxies.PaymentTypes.valueOf((String) obj);
	}

	/**
	 * Set value of Payment
	 * @param payment
	 */
	public final void setPayment(pizzamario.proxies.PaymentTypes payment)
	{
		setPayment(getContext(), payment);
	}

	/**
	 * Set value of Payment
	 * @param context
	 * @param payment
	 */
	public final void setPayment(IContext context, pizzamario.proxies.PaymentTypes payment)
	{
		if (payment != null)
			getMendixObject().setValue(context, MemberNames.Payment.toString(), payment.toString());
		else
			getMendixObject().setValue(context, MemberNames.Payment.toString(), null);
	}

	/**
	 * @return value of Total
	 */
	public final Integer getTotal()
	{
		return getTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Total
	 */
	public final Integer getTotal(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Total.toString());
	}

	/**
	 * Set value of Total
	 * @param total
	 */
	public final void setTotal(Integer total)
	{
		setTotal(getContext(), total);
	}

	/**
	 * Set value of Total
	 * @param context
	 * @param total
	 */
	public final void setTotal(IContext context, Integer total)
	{
		getMendixObject().setValue(context, MemberNames.Total.toString(), total);
	}

	/**
	 * @return value of Location
	 */
	public final String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final String getLocation(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(IContext context, String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of IsGenerated
	 */
	public final Boolean getIsGenerated()
	{
		return getIsGenerated(getContext());
	}

	/**
	 * @param context
	 * @return value of IsGenerated
	 */
	public final Boolean getIsGenerated(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.IsGenerated.toString());
	}

	/**
	 * Set value of IsGenerated
	 * @param isgenerated
	 */
	public final void setIsGenerated(Boolean isgenerated)
	{
		setIsGenerated(getContext(), isgenerated);
	}

	/**
	 * Set value of IsGenerated
	 * @param context
	 * @param isgenerated
	 */
	public final void setIsGenerated(IContext context, Boolean isgenerated)
	{
		getMendixObject().setValue(context, MemberNames.IsGenerated.toString(), isgenerated);
	}

	/**
	 * @return value of Order_Customer
	 */
	public final pizzamario.proxies.Customer getOrder_Customer() throws CoreException
	{
		return getOrder_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Customer
	 */
	public final pizzamario.proxies.Customer getOrder_Customer(IContext context) throws CoreException
	{
		pizzamario.proxies.Customer result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Customer.toString());
		if (identifier != null)
			result = pizzamario.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Order_Customer
	 * @param order_customer
	 */
	public final void setOrder_Customer(pizzamario.proxies.Customer order_customer)
	{
		setOrder_Customer(getContext(), order_customer);
	}

	/**
	 * Set value of Order_Customer
	 * @param context
	 * @param order_customer
	 */
	public final void setOrder_Customer(IContext context, pizzamario.proxies.Customer order_customer)
	{
		if (order_customer == null)
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), order_customer.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pizzamario.proxies.Order that = (pizzamario.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PizzaMario.Order";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
