// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pizzamario.proxies;

public enum Toppings
{
	Mozzarella(new String[][] { new String[] { "en_US", "Mozzarella" } }),
	Tomato(new String[][] { new String[] { "en_US", "Tomato" } }),
	Ham(new String[][] { new String[] { "en_US", "Ham" } }),
	Mushrooms(new String[][] { new String[] { "en_US", "Mushrooms" } }),
	Olives(new String[][] { new String[] { "en_US", "Olives" } }),
	Onions(new String[][] { new String[] { "en_US", "Onions" } }),
	Pepperoni(new String[][] { new String[] { "en_US", "Pepperoni" } });

	private java.util.Map<String,String> captions;

	private Toppings(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
