// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package performancetool.actions;

import java.util.HashMap;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import performancetool.XPath;
import performancetool.proxies.MicroflowPerformance;

/**
 * ; separated list of markers
 */
public class GetListMicroflowPerformanceByMarkerList extends UserAction<java.util.List<IMendixObject>>
{
	private String MarkerList;
	private Long ChunkSize;
	private Long ChunkIndex;

	public GetListMicroflowPerformanceByMarkerList(String MarkerList, Long ChunkSize, Long ChunkIndex)
	{
		super();
		this.MarkerList = MarkerList;
		this.ChunkSize = ChunkSize;
		this.ChunkIndex = ChunkIndex;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		Map<String, String> sortMap = new HashMap<String,String>();
		sortMap.put("AutoID", "ASC");
		
		XPath<MicroflowPerformance> xPath = XPath.create(this.getContext(), MicroflowPerformance.class);
		boolean initial = true;
		for(String marker:MarkerList.split(";")) {
			if (marker.isEmpty()) continue;
			if (initial) {
				xPath = xPath.eq(MicroflowPerformance.MemberNames.Marker, marker);
				initial = false;
			} else {
				xPath = xPath.or().eq(MicroflowPerformance.MemberNames.Marker, marker);
			}
		}
		xPath = xPath.addSortingAsc(MicroflowPerformance.MemberNames.AutoID).limit(ChunkSize.intValue()).offset(ChunkIndex.intValue()*ChunkSize.intValue());
        return xPath.allMendixObjects();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetListMicroflowPerformanceByMarkerList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
