// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package performancetool.actions;

import nl.mansystems.performancetool.PerformanceToolLogSubscriber;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class PerformanceToolIsRunning extends UserAction<Boolean>
{
	public PerformanceToolIsRunning()
	{
		super();
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

        try {
        	return PerformanceToolLogSubscriber.getInstance().performanceMeasurementIsRunning();
        }
        catch (final Throwable ex) {
            Core.getLogger("Logging").error("Exception while trying to get the status of the log subscriber.", ex);
            return Boolean.FALSE;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "PerformanceToolIsRunning";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
