// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package performancetool.actions;

import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class StartPerformanceMeasurement_Java extends UserAction<Boolean>
{
	private Boolean MeasureActions;
	private String IncludeMicroflows;
	private Boolean TraceSQLStatements;
	private Long Threshold;
	private String Marker;
	private Long Duration;
	private Long MaxActions;
	private Long MaxSQL;
	private Boolean PreProcess;
	private String ExcludeMicroflows;

	public StartPerformanceMeasurement_Java(Boolean MeasureActions, String IncludeMicroflows, Boolean TraceSQLStatements, Long Threshold, String Marker, Long Duration, Long MaxActions, Long MaxSQL, Boolean PreProcess, String ExcludeMicroflows)
	{
		super();
		this.MeasureActions = MeasureActions;
		this.IncludeMicroflows = IncludeMicroflows;
		this.TraceSQLStatements = TraceSQLStatements;
		this.Threshold = Threshold;
		this.Marker = Marker;
		this.Duration = Duration;
		this.MaxActions = MaxActions;
		this.MaxSQL = MaxSQL;
		this.PreProcess = PreProcess;
		this.ExcludeMicroflows = ExcludeMicroflows;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		nl.mansystems.performancetool.PerformanceToolLogSubscriber.getInstance().startPerformanceMeasurement(MeasureActions, IncludeMicroflows, ExcludeMicroflows, TraceSQLStatements, Threshold, Marker, Duration, MaxActions, MaxSQL, PreProcess);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "StartPerformanceMeasurement_Java";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
