// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package performancetool.actions;

import nl.mansystems.performancetool.PerformanceToolLogSubscriber;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class StopPerformanceMeasurement_Java extends UserAction<Boolean>
{
	public StopPerformanceMeasurement_Java()
	{
		super();
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		nl.mansystems.performancetool.PerformanceToolLogSubscriber.getInstance().stopPerformanceMeasurement(this.getContext());
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "StopPerformanceMeasurement_Java";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
