// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package performancetool.actions;

import com.mendix.systemwideinterfaces.core.UserAction;
import nl.mansystems.performancetool.PerformanceToolLogSubscriber;
import com.mendix.core.Core;

/**
 * Stops the log subscriber that writes log messages to the database as "Logging.Message" objects.
 * 
 * Returns: 'true' on success, 'false' on failure.
 */
public class StopLogSubscriber extends UserAction<Boolean>
{
	public StopLogSubscriber()
	{
		super();
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

        try {
        	PerformanceToolLogSubscriber.getInstance().stop();
        }
        catch (final Throwable ex) {
            Core.getLogger("Logging").error("Exception while trying to stop the log subscriber.", ex);
            return Boolean.FALSE;
        }
        return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "StopLogSubscriber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
