// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pizzamario.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class ExtraTopping
{
	private final IMendixObject extraToppingMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PizzaMario.ExtraTopping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ExtraTopping_OrderLine("PizzaMario.ExtraTopping_OrderLine"),
		ExtraTopping_Topping("PizzaMario.ExtraTopping_Topping");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public ExtraTopping(IContext context)
	{
		this(context, Core.instantiate(context, "PizzaMario.ExtraTopping"));
	}

	protected ExtraTopping(IContext context, IMendixObject extraToppingMendixObject)
	{
		if (extraToppingMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("PizzaMario.ExtraTopping", extraToppingMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PizzaMario.ExtraTopping");

		this.extraToppingMendixObject = extraToppingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new ExtraTopping(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static pizzamario.proxies.ExtraTopping create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "PizzaMario.ExtraTopping");
		return new pizzamario.proxies.ExtraTopping(context, mendixObject);
	}

	/**
	 * @deprecated Use 'ExtraTopping.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pizzamario.proxies.ExtraTopping initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pizzamario.proxies.ExtraTopping.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pizzamario.proxies.ExtraTopping initialize(IContext context, IMendixObject mendixObject)
	{
		return new pizzamario.proxies.ExtraTopping(context, mendixObject);
	}

	public static pizzamario.proxies.ExtraTopping load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pizzamario.proxies.ExtraTopping.initialize(context, mendixObject);
	}

	public static java.util.List<pizzamario.proxies.ExtraTopping> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pizzamario.proxies.ExtraTopping> result = new java.util.ArrayList<pizzamario.proxies.ExtraTopping>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PizzaMario.ExtraTopping" + xpathConstraint))
			result.add(pizzamario.proxies.ExtraTopping.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ExtraTopping_OrderLine
	 */
	public final pizzamario.proxies.OrderLine getExtraTopping_OrderLine() throws CoreException
	{
		return getExtraTopping_OrderLine(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtraTopping_OrderLine
	 */
	public final pizzamario.proxies.OrderLine getExtraTopping_OrderLine(IContext context) throws CoreException
	{
		pizzamario.proxies.OrderLine result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExtraTopping_OrderLine.toString());
		if (identifier != null)
			result = pizzamario.proxies.OrderLine.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExtraTopping_OrderLine
	 * @param extratopping_orderline
	 */
	public final void setExtraTopping_OrderLine(pizzamario.proxies.OrderLine extratopping_orderline)
	{
		setExtraTopping_OrderLine(getContext(), extratopping_orderline);
	}

	/**
	 * Set value of ExtraTopping_OrderLine
	 * @param context
	 * @param extratopping_orderline
	 */
	public final void setExtraTopping_OrderLine(IContext context, pizzamario.proxies.OrderLine extratopping_orderline)
	{
		if (extratopping_orderline == null)
			getMendixObject().setValue(context, MemberNames.ExtraTopping_OrderLine.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExtraTopping_OrderLine.toString(), extratopping_orderline.getMendixObject().getId());
	}

	/**
	 * @return value of ExtraTopping_Topping
	 */
	public final pizzamario.proxies.Topping getExtraTopping_Topping() throws CoreException
	{
		return getExtraTopping_Topping(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtraTopping_Topping
	 */
	public final pizzamario.proxies.Topping getExtraTopping_Topping(IContext context) throws CoreException
	{
		pizzamario.proxies.Topping result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExtraTopping_Topping.toString());
		if (identifier != null)
			result = pizzamario.proxies.Topping.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExtraTopping_Topping
	 * @param extratopping_topping
	 */
	public final void setExtraTopping_Topping(pizzamario.proxies.Topping extratopping_topping)
	{
		setExtraTopping_Topping(getContext(), extratopping_topping);
	}

	/**
	 * Set value of ExtraTopping_Topping
	 * @param context
	 * @param extratopping_topping
	 */
	public final void setExtraTopping_Topping(IContext context, pizzamario.proxies.Topping extratopping_topping)
	{
		if (extratopping_topping == null)
			getMendixObject().setValue(context, MemberNames.ExtraTopping_Topping.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExtraTopping_Topping.toString(), extratopping_topping.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return extraToppingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pizzamario.proxies.ExtraTopping that = (pizzamario.proxies.ExtraTopping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PizzaMario.ExtraTopping";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
