// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class UsageInfo
{
	private final IMendixObject usageInfoMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "Administration.UsageInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Date("Date"),
		NumberOfConcurrentUsers("NumberOfConcurrentUsers");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public UsageInfo(IContext context)
	{
		this(context, Core.instantiate(context, "Administration.UsageInfo"));
	}

	protected UsageInfo(IContext context, IMendixObject usageInfoMendixObject)
	{
		if (usageInfoMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("Administration.UsageInfo", usageInfoMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a Administration.UsageInfo");

		this.usageInfoMendixObject = usageInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new UsageInfo(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static administration.proxies.UsageInfo create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "Administration.UsageInfo");
		return new administration.proxies.UsageInfo(context, mendixObject);
	}

	/**
	 * @deprecated Use 'UsageInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static administration.proxies.UsageInfo initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return administration.proxies.UsageInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static administration.proxies.UsageInfo initialize(IContext context, IMendixObject mendixObject)
	{
		return new administration.proxies.UsageInfo(context, mendixObject);
	}

	public static administration.proxies.UsageInfo load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return administration.proxies.UsageInfo.initialize(context, mendixObject);
	}

	public static java.util.List<administration.proxies.UsageInfo> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<administration.proxies.UsageInfo> result = new java.util.ArrayList<administration.proxies.UsageInfo>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//Administration.UsageInfo" + xpathConstraint))
			result.add(administration.proxies.UsageInfo.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of NumberOfConcurrentUsers
	 */
	public final Integer getNumberOfConcurrentUsers()
	{
		return getNumberOfConcurrentUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfConcurrentUsers
	 */
	public final Integer getNumberOfConcurrentUsers(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.NumberOfConcurrentUsers.toString());
	}

	/**
	 * Set value of NumberOfConcurrentUsers
	 * @param numberofconcurrentusers
	 */
	public final void setNumberOfConcurrentUsers(Integer numberofconcurrentusers)
	{
		setNumberOfConcurrentUsers(getContext(), numberofconcurrentusers);
	}

	/**
	 * Set value of NumberOfConcurrentUsers
	 * @param context
	 * @param numberofconcurrentusers
	 */
	public final void setNumberOfConcurrentUsers(IContext context, Integer numberofconcurrentusers)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfConcurrentUsers.toString(), numberofconcurrentusers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return usageInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administration.proxies.UsageInfo that = (administration.proxies.UsageInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "Administration.UsageInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
